//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.22 at 04:15:05 PM GMT+02:00 
//


package eg.com.dataload.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;




/**
 * <p>Java class for DataType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DataType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Date"/>
 *     &lt;enumeration value="Number"/>
 *     &lt;enumeration value="String"/>
 *     &lt;enumeration value="Double"/>
 *     &lt;enumeration value="Null"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DataType")
@XmlEnum
public enum DataType {

    @XmlEnumValue("Date")
    DATE("Date"),
    @XmlEnumValue("Number")
    NUMBER("Number"),
    @XmlEnumValue("String")
    STRING("String"),
    @XmlEnumValue("Double")
    DOUBLE("Double"),    
    @XmlEnumValue("Null")
    NULL("Null");
    private final String value;

    DataType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataType valueOff(String value){
    	for(DataType dt : DataType.values() ){
    		if(dt.value().equalsIgnoreCase(value)){
    			return dt;
    		}
    	}
    	
    	throw new IllegalArgumentException("Enum ["+DataType.class+"] has no constant for value ["+value+"] ");
    	
    }
    
   
    

}
