//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.25 at 09:59:43 AM GMT+02:00 
//


package eg.com.dataload.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eg.com.dataload.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eg.com.dataload.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link Entity.Colomn }
     * 
     */
    public Entity.Colomn createEntityColomn() {
        return new Entity.Colomn();
    }

    /**
     * Create an instance of {@link Entity.Parameters }
     * 
     */
    public Entity.Parameters createEntityParameters() {
        return new Entity.Parameters();
    }

    /**
     * Create an instance of {@link Entity.Colomn.Mapping }
     * 
     */
    public Entity.Colomn.Mapping createEntityColomnMapping() {
        return new Entity.Colomn.Mapping();
    }

    /**
     * Create an instance of {@link Entity.Parameters.Param }
     * 
     */
    public Entity.Parameters.Param createEntityParametersParam() {
        return new Entity.Parameters.Param();
    }

}
